### ISSUE TITLE
Custom types do not rehydrate with constructor intact

### ISSUE THREAD

**Issue by timoxley** [carlos8f/hydration#2]
Currently hydration only works with the built-in types you set up such as regex/date/etc, and doesn't work if the object you're hydrating has a custom constructor

```js
  it('preserves constructors during rehydration', function() {
    var CustomType = function(){}
    var obj = new CustomType()
    var dehydrated = hydration.dehydrate(obj);
    var hydrated = hydration.hydrate(dehydrated);
    assert.strictEqual(obj.constructor, hydrated.constructor, 'rehydrated object maintains original constructor')
  })
```
Not exactly sure how you solve that as it's a tricky issue, simply saving a `toString()` of the constructor isn't guaranteed to work since it loses its original scope, but perhaps allowing custom types to supply custom `hydrate` and `dehydrate` methods (or even use `toJSON`) if they exist, could be a start.

**Comment by carlos8f** [comment]
@timoxley hydration 1.0.0 is now available with custom type support curtesy of @mvayngrib .
